### ISSUE TITLE
Meta: Consolidate Migration, Seeds and data dumps

### ISSUE THREAD

**Issue by dmohns** [EnAccess/micropowermanager#207]
**Rationale:**

Currently, the way the database "data" is managed in MPM is highly inconsistent, hard to manage and generally confusing for new users.

**Scope:**

The high-level goal is to have an intuitive handling for data manipulation methods in MPM.

**Ticket List:**

- [x] https://github.com/EnAccess/micropowermanager/issues/209
- [x] https://github.com/EnAccess/micropowermanager/issues/90
- [ ] https://github.com/EnAccess/micropowermanager/issues/208
- [x] https://github.com/EnAccess/micropowermanager/issues/227
- [x] https://github.com/EnAccess/micropowermanager/issues/228
- [x] https://github.com/EnAccess/micropowermanager/issues/92
- [x] https://github.com/EnAccess/micropowermanager/issues/114
