### ISSUE TITLE
Meta: Provide a fully-working Demo setup

### ISSUE THREAD

**Issue by dmohns** [EnAccess/micropowermanager#221]
**Rationale:**

A fully working demo and development setup is required for 

- User exploration and evaluation of the MPM functionality
- Efficient development of features of the MPM

Currently, there is a lot of dummy data missing, which makes understanding and developing for the affected features very hard.

**Scope:**

The high-level goal is to have a fully working demo setup with reasonable dummy data.

**Pre-requisites:**

- [ ] https://github.com/EnAccess/micropowermanager/issues/207

**Ticket List:**

- [x] https://github.com/EnAccess/micropowermanager/issues/222
- [ ] https://github.com/EnAccess/micropowermanager/issues/153
- [x] https://github.com/EnAccess/micropowermanager/issues/87

**Comment by dmohns** [comment]
Even though not all the steps from the original list has been implemented yet, we are closing this Meta ticket as the Demo version is now ready to use.
